[project]
name = "merge"
version = "0.1.0"
description = "A collection of transformers based implementation of various papers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.1.3",
    "torch>=2.5.1",
]
